kind: Deployment
apiVersion: apps/v1
metadata:
  name: inventory-database
spec:
  strategy:
    type: Recreate
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
  replicas: 1
  selector:
      matchLabels:
        name: inventory-database
  template:
    metadata:
      labels:
        name: inventory-database
    spec:
      volumes:
        - name: inventory-database-data
          emptyDir: {}
      containers:
        - resources:
            limits:
              memory: 512Mi
          readinessProbe:
            exec:
              command:
                - /usr/libexec/check-container
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: postgresql
          livenessProbe:
            exec:
              command:
                - /usr/libexec/check-container
                - '--live'
            initialDelaySeconds: 120
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: inventory-database
                  key: database-user
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: inventory-database
                  key: database-password
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: inventory-database
                  key: database-name
          securityContext:
            capabilities: {}
            privileged: false
          ports:
            - containerPort: 5432
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: inventory-database-data
              mountPath: /var/lib/pgsql/data
          terminationMessagePolicy: File
          image: registry.redhat.io/rhel8/postgresql-10
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---
kind: Secret
apiVersion: v1
metadata:
  name: inventory-database
data:
  database-name: aW52ZW50b3J5
  database-password: bXlzZWNyZXRwYXNzd29yZA==
  database-user: aW52ZW50b3J5
type: Opaque

---
kind: Service
apiVersion: v1
metadata:
  name: inventory-database
spec:
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    name: inventory-database


