---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: coolstore-postgresql
spec:
  strategy:
    type: Recreate
  triggers:
  - type: ImageChange
    imageChangeParams:
      automatic: true
      containerNames:
      - coolstore-postgresql
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: postgresql:latest
  - type: ConfigChange
  replicas: 1
  selector:
    matchLabels:
      name: coolstore-postgresql
  template:
    metadata:
      labels:
        name: coolstore-postgresql
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: coolstore-postgresql
        image: registry.redhat.io/rhel8/postgresql-10
        imagePullPolicy: IfNotPresent
        readinessProbe:
          exec:
            command:
            - "/bin/sh"
            - "-i"
            - "-c"
            - psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d $POSTGRESQL_DATABASE -c
              'SELECT 1'
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        ports:
        - containerPort: 5432
          protocol: TCP
        env:
        - name: POSTGRESQL_USER
          value: coolstore
        - name: POSTGRESQL_PASSWORD
          value: coolstore123
        - name: POSTGRESQL_DATABASE
          value: monolith


---
kind: Service
apiVersion: v1
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    name: coolstore-postgresql
metadata:
  name: coolstore-postgresql
  labels:
    application: coolstore
  annotations:
    description: The database server's port.
