kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: catalog-springboot
  labels:
    app: catalog-springboot
    app.kubernetes.io/component: catalog-springboot
    app.kubernetes.io/instance: catalog-springboot
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
  replicas: 1
  selector:
    deploymentconfig: catalog-springboot
  template:
    metadata:
      labels:
        deploymentconfig: catalog-springboot
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - name: catalog-springboot
          image: quay.io/fuangwit/coolstore-catalog:0.2
          ports:
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8778
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
          env:
            - name: JAVA_OPTS_APPEND
              value: '-Dspring.profiles.active=openshift'
            - name: inventory.url
              value: 'inventory.inventory.svc.cluster.local:8080'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---
kind: Service
apiVersion: v1
metadata:
  name: catalog-springboot
  labels:
    app: catalog-springboot
    app.kubernetes.io/component: catalog-springboot
    app.kubernetes.io/instance: catalog-springboot
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: 8443-tcp
      protocol: TCP
      port: 8443
      targetPort: 8443
    - name: 8778-tcp
      protocol: TCP
      port: 8778
      targetPort: 8778
  selector:
    deploymentconfig: catalog-springboot


---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: catalog-springboot
  labels:
    app: catalog-springboot
    app.kubernetes.io/component: catalog-springboot
    app.kubernetes.io/instance: catalog-springboot
spec:
  to:
    kind: Service
    name: catalog-springboot
    weight: 100
  port:
    targetPort: 8080-tcp
  wildcardPolicy: None


