---
kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: inventory
  labels:
    app.kubernetes.io/name: inventory
    app.openshift.io/runtime: quarkus
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
  replicas: 1
  selector:
    app.kubernetes.io/name: inventory
  template:
    metadata:
      labels:
        app.kubernetes.io/name: inventory
        app.openshift.io/runtime: quarkus
    spec:
      containers:
        - resources: {}
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            timeoutSeconds: 10
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: inventory
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            timeoutSeconds: 10
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
          image: quay.io/fuangwit/coolstore-inventory:0.2
      restartPolicy: Always
      terminationGracePeriodSeconds: 30


---
kind: Service
apiVersion: v1
metadata:
  name: inventory
  labels:
    app.kubernetes.io/name: inventory
    app.openshift.io/runtime: quarkus
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: inventory
  type: ClusterIP

---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: inventory
  labels:
    app.kubernetes.io/name: inventory
    app.openshift.io/runtime: quarkus
spec:
  path: /
  to:
    kind: Service
    name: inventory
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None

